services:
  spark-master:
    image: apache/spark:3.5.1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    hostname: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./wordcount:/opt/spark-demo

  spark-worker:
    image: apache/spark:3.5.1
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./wordcount:/opt/spark-demo
