services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=demo
    env_file:
      - ./config/hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    depends_on:
      - namenode
    env_file:
      - ./config/hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    ports:
      - "8088:8088"
    env_file:
      - ./config/hadoop.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    depends_on:
      - resourcemanager
      - datanode
    env_file:
      - ./config/hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
